DROP DATABASE github;

CREATE DATABASE github;

USE github;

CREATE TABLE repos (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  username CHAR(255) NOT NULL,
  name TEXT NOT NULL,
  html_url TEXT NOT NULL,
  stars INTEGER
);
